### ISSUE TITLE
Documentation for percentObjSize

### ISSUE THREAD

**Issue by cam-c7** [blaine-t/hgl-java#1]
extra PercentX in documentation for percentObjSize function
When you use:  `percentObjSize(null, eventMask, eventMask);`
documentation has a blank "PercentX" in addition to correct PercentX documentation

**Comment by blaine-t** [comment]
[Fixed](https://github.com/blaine-t/hgl-java/commit/d3f78fdaaad84ef6d2f96e0c94590a0cbe8cc61f)
